[workspace]
authors = ["JoseEOAS <jvalenti@eoas.ubc.ca>"]
channels = ["conda-forge"]
name = "analysis-jose"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
arrow = "*"
bottleneck = "*"
cliff = "*"
cmocean = "*"
coverage = "*"
dask = "*"
f90nml = "*"
gsw = "*"
ipdb = "*"
ipython = "*"
jupyterlab = "*"
lxml = "*"
matplotlib = "*"
nbsphinx = "*"
netcdf4 = "*"
numpy = "*"
pandas = "*"
pip = "*"
progressbar = "*"
pytest = "*"
python = "3.11.*"
pytz = "*"
python-dateutil = "*"
pyyaml = "*"
requests = "*"
retrying = "*"
scipy = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
xarray = "*"
zeep = "*"
h5netcdf = ">=1.8.1,<2"
jupyter = "*"
yaml = "*"

[feature.Parcels.dependencies]
numpy = "1.26.*"
pandas = "2.2.*"
parcels = "*"
scipy = "1.11.*"
xarray = "2024.6.0.*"
zarr = "2.16.*"
mpich = "*"
mpi4py = "*"

[feature.SHEM.dependencies]
python = "3.11.*"
pandas = "*"
scipy = "*"
xarray = "*"
zarr = "*"
cmocean = "*"
yaml = "*"

[feature.SHEM.pypi-dependencies]
permetrics = "*"

[environments]
parcels = ["Parcels"]
shem = ["SHEM"]
